### ISSUE TITLE
Support for index lifecycle management (ILM)

### ISSUE THREAD

**Issue by cdenneen** [voxpupuli/puppet-elasticsearch#1038]
Ability to update and maintain lifecycle policies
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/index-lifecycle-management-api.html

https://www.elastic.co/guide/en/elasticsearch/reference/6.8/index-lifecycle-management.html

**Comment by tylerjl** [comment]
Thanks @cdenneen! This seems like something that would fit the profile of other, REST-based resources the module handles.

**Comment by cdenneen** [comment]
@tylerjl @fatmcgav any chance to get this implemented with the 7.0 work coming?
