### ISSUE TITLE
'jvm.options' (prerequisite, required file) is unmanaged by module

### ISSUE THREAD

**Issue by grant-veepshosting** [voxpupuli/puppet-elasticsearch#1093]
## Bug description
The file "jvm.options" is not managed by the current 'master' branch of the module, however it's required for an Augueas lens in manifests/config.pp lines 185 - 193.

When installing new nodes, this file is present and the current Augueas lens works as desired.

When migrating clients from the legacy Forge version of the module (v6.4.0) this file is deliberately removed by the module (config.pp, lines 72,73), and as such never put into place again to make everything work correctly, unless done manually.

In addition to being able to override the default provided array of options from 'common.yaml', the Java Memory parameters should be available to configure as top level parameters.

**Comment by h-haaks** [comment]
Fixed by #1202
