### ISSUE TITLE
When restart_config_change is set to false Elasticsearch is still restarted

### ISSUE THREAD

**Issue by scornelissen85** [voxpupuli/puppet-elasticsearch#1113]
* Module version: 7.0.0
* Puppet version: 6.x
* OS and version: RedHat 7

## Bug description

When the parameter `restart_config_change` on the class `elasticsearch` is set to `false`, Elasticsearch is still restarted by line 514: https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/init.pp#L514 (there is an hardcoded notify from `Class['elasticsearch::config']` to `Class['elasticsearch::service']` which will result in a restart of the Elasticsearch service.

**Comment by scornelissen85** [comment]
This seems to be  a duplicate of #1111, while that one resolved it by never notify Elasticsearch service, even when `restarton_config` is set to `true`.

**Comment by oniGino** [comment]
i think its fixed in #1114 but i don't think a release has been made yet

**Comment by smortex** [comment]
@oniGino 8.0.0 should include this. Can you try it and report the outcome? Thanks!

**Comment by oniGino** [comment]
yes it is, thanks! i was still pulling from the elastic repo instead of voxpopuli

i think its safe to close this

**Comment by smortex** [comment]
Awesome, thanks!
