### ISSUE TITLE
Elasticsearch::Config/Java_ks causes restarts every puppet run

### ISSUE THREAD

**Issue by cmlambertus** [voxpupuli/puppet-elasticsearch#1129]
* Module version: master and 7.0.0
* Puppet version: 7.12.0
* OS and version: Ubuntu 20.04

## Bug description

Despite setting the following:

elasticsearch::restart_on_change: false
elasticsearch::restart_config_change: false
elasticsearch::restart_package_change: false
elasticsearch::restart_plugin_change: false

Every time puppet runs, ES is restarted due to:

Notice: /Stage[main]/Elasticsearch::Config/Java_ks[elasticsearch_node]/ensure: ensure changed 'present' to 'latest'
Debug: /Stage[main]/Elasticsearch::Config/Java_ks[elasticsearch_node]: The container Class[Elasticsearch::Config] will propagate my refresh event

Notice: /Stage[main]/Elasticsearch::Config/Java_ks[elasticsearch_ca]/ensure: created (corrective)
Debug: /Stage[main]/Elasticsearch::Config/Java_ks[elasticsearch_ca]: The container Class[Elasticsearch::Config] will propagate my refresh event

**Comment by XerockXMG** [comment]
Running into this issue myself. It's quite obnoxious for the service to restart every puppet run.

**Comment by oniGino** [comment]
I have the same issue, is this package still maintained?

**Comment by oniGino** [comment]
i think its fixed in #1114 but i don't think a release has been made yet

**Comment by smortex** [comment]
@oniGino 8.0.0 should include this.  Can you try it and report the outcome?  Thanks!

**Comment by oniGino** [comment]
yes it is, thanks! i was still pulling from the elastic repo instead of voxpopuli

i think its safe to close this

**Comment by smortex** [comment]
Fine, thanks!
