### ISSUE TITLE
typo in config.pp

### ISSUE THREAD

**Issue by cmlambertus** [voxpupuli/puppet-elasticsearch#1130]
https://github.com/voxpupuli/puppet-elasticsearch/blob/1068b7c8363b723c0573be398e4031334c453411/manifests/config.pp#L209

notify    => $::elaticsearch::_notify_service,

**Comment by smortex** [comment]
```diff
-        notify    => $::elaticsearch::_notify_service,
+        notify    => $::elasticsearch::_notify_service,
```
