### ISSUE TITLE
Release 8.0.0 not tagged

### ISSUE THREAD

**Issue by towo** [voxpupuli/puppet-elasticsearch#1145]
## Affected Puppet, Ruby, OS and module versions/distributions

- Module version: 7.0.0 / master

## What are you seeing

No tag since v7

## What behaviour did you expect instead

Git tag for release 8.0.0 (probably for a609c0c27ed033df26421b15dd7fa9664b318d1c)

**Comment by smortex** [comment]
The tag should be on the merge commit: 9430213d002f8d6f45b1e4a4bf24525e5d5f7696

I'll take care of this, thanks!

**Comment by towo** [comment]
Ah, right, I meant to say release and got confused. Thanks!
