### ISSUE TITLE
Could not evaluate: undefined method `join' for :name:Symbol

### ISSUE THREAD

**Issue by stjmt** [voxpupuli/puppet-elasticsearch#1155]
Hello,

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:  6.16.0-1buster 600
- Ruby: 2.5.0
- Distribution: Linux Debian 10
- Module version: 8.0.1

## How to reproduce (e.g Puppet code you use)

elasticsearch::user { 'logstash_writer':
          ensure   => 'present',
          password => 'mapasswordabcd1234',
          roles    => ['logstash_write_role'],
        }

## What are you seeing

Error :
Info: Computing checksum on file /etc/elasticsearch/users_roles
Error: /Stage[main]/Elastics::Elasticsearch::Role_user/Elasticsearch::User[logstash_writer]/Elasticsearch_user_roles[logstash_writer]: Could not evaluate: undefined method `join' for :name:Symbol

## Any additional information you'd like to impart

I suppose a problem with join in https://github.com/voxpupuli/puppet-elasticsearch/blob/master/lib/puppet/provider/elastic_user_roles.rb (L 51)

**Comment by AxisNL** [comment]
I have the same problem! Ubuntu 20.04LTS, puppet-agent 7.15.0-1focal, ruby 1:2.7+1, module 8.0.1

**Comment by otterz** [comment]
I'm facing the same issue with version 8.0.2.

I made a [PR](https://github.com/voxpupuli/puppet-elasticsearch/pull/1165) to fix this issue.
