### ISSUE TITLE
ssl=true and version is not defined, gives an error

### ISSUE THREAD

**Issue by asusk7m550** [voxpupuli/puppet-elasticsearch#1173]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: -
- Distribution: all
- Module version: v8.0.2

## How to reproduce (e.g Puppet code you use)

```
class { 'elasticsearch' :
  ssl                  => true,
  ca_certificate       => '/path/to/ca.pem',
  certificate          => '/path/to/cert.pem',
  private_key          => '/path/to/key.pem',
  keystore_password    => 'keystorepassword',
}
```

## What are you seeing

When you want SSL enabled and use the default packages from the OS (so not setting a version), there is an error in getting the catalog.

## What behaviour did you expect instead

When no version is defined, expect a version of 7 or higher and add the tls_config from that one.

## Output log
`
Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Boolean (file: /etc/puppetlabs/code/environments/xxx/modules/elasticsearch/manifests/config.pp, line: 96, column: 11)`

**Comment by YokaiRick** [comment]
Hi, thanks this also fixes https://github.com/voxpupuli/puppet-elasticsearch/issues/1174
At least partly.. shouldn't be the if case not be:

```
if ($elasticsearch::version == false and versioncmp($elasticsearch::version, '7') >= 0)
```

cause rn, when i set the version to false, it rolls out the tls config for ela6 and not for ela7

see also here:
>What behaviour did you expect instead
>When no version is defined, expect a version of 7 or higher and add the tls_config from that one
