### ISSUE TITLE
warnings when used with stlib 9.

### ISSUE THREAD

**Issue by robertc99** [voxpupuli/puppet-elasticsearch#1201]
Module isnt fully compatible with stdlib 9.
Generates the following warning

Warning: This function is deprecated, please use stdlib::merge instead. at ["/etc/puppetlabs/code/environments/elk_staging/r10k/modules/elasticsearch/manifests/config.pp", 24]:["/etc/puppetlabs/code/environments/elk_staging/r10k/modules/elasticsearch/manifests/init.pp", 476]
   (location: /etc/puppetlabs/code/environments/elk_staging/r10k/modules/stdlib/lib/puppet/functions/deprecation.rb:35:in `deprecation')

**Comment by h-haaks** [comment]
fixed by #1217
